// Editorial content is maintained here. Match results are not a live feed.
window.svzData = {
  updatedAt: "02.10.2026",
  club: {
    name: "SV Zweckel 23 e. V.",
    address: "Dorstener Straße 43, 45966 Gladbeck",
    email: "info@svzweckel.de",
    phone: "+49204351743",
    officialUrl: "https://www.svzweckel.de/",
    footballUrl:
      "https://www.fussball.de/verein/sv-zweckel-westfalen/-/id/00ES8GN8OC00001OVV0AG08LVUPGND5I",
    shopUrl: "https://team.jako.com/de-de/team/sv_zweckel_23_e_v_/",
  },
  news: [
    {
      slug: "legendenspiel-2026",
      category: "Verein",
      date: "2026-09-30",
      title: "Die Legenden kehren zurück.",
      excerpt:
        "Am 3. Oktober trifft Zweckeler Fußballgeschichte auf Gladbecker Legenden. Anpfiff ist um 15 Uhr in der Uli-Simon-Arena.",
      body: "Die Vereinsankündigung lädt ehemalige Spieler und Fans zum Wiedersehen am Kunstrasenplatz ein. Für die Mitspieler ist das Treffen bereits um 14 Uhr an den Umkleiden vorgesehen.",
      image: "assets/team_sitzkreis_1_.webp",
      alt: "Zweckeler Spieler im Kreis am Spielfeldrand; Archivmotiv",
      imageLabel: "Vereinsarchiv",
      sourceUrl: "https://www.svzweckel.de/?p=19532",
    },
    {
      slug: "grafenwald-zweckel-september-2026",
      category: "1. Mannschaft",
      date: "2026-09-27",
      title: "Führung reicht in Grafenwald nicht.",
      excerpt:
        "Nach einer 1:0-Pausenführung verliert der SVZ beim VfL Grafenwald mit 1:4.",
      body: "Sajad Omar brachte die Zweckeler in Führung. Nach der Pause drehte Grafenwald die Begegnung und erzielte in der Schlussphase drei weitere Treffer. Der vollständige Spielbericht steht auf der Vereinswebsite.",
      image: "assets/header_bild_1.webp",
      alt: "Flutlicht über einem Fußballplatz; Symbolbild",
      imageLabel: "Symbolbild",
      sourceUrl: "https://www.svzweckel.de/?p=19529",
    },
    {
      slug: "schalke-camp-oktober-2026",
      category: "Jugend",
      date: "2026-09-26",
      title: "Drei Tage Fußball. Ganz viel Schalke.",
      excerpt:
        "Die FC Schalke 04 Fußballschule kommt vom 28. bis 30. Oktober nach Zweckel.",
      body: "Das Camp richtet sich an Kinder von 7 bis 14 Jahren. Geplant sind Training, Wettbewerbe und Turniere. Informationen zur Anmeldung findest du in der offiziellen Vereinsmeldung.",
      image: "assets/blog_bild_1.webp",
      alt: "Fußball und Notizbuch am Spielfeldrand; Symbolbild",
      imageLabel: "Symbolbild",
      sourceUrl: "https://www.svzweckel.de/?p=19482",
    },
  ],
  match: {
    date: "27.09.2026",
    home: "VfL Grafenwald",
    homeShort: "GRA",
    away: "SV Zweckel",
    awayShort: "SVZ",
    score: "4:1",
    halftime: "0:1",
    status: "Endstand",
    sourceUrl: "https://www.svzweckel.de/?p=19529",
  },
  products: [
    {
      id: "glory",
      name: "Trikot Glory",
      type: "Kurzarm",
      color: "Weiß / Schwarz",
      front: "assets/JAKO_Trikot_Glory_kurzarm_front.jpg",
      back: "assets/JAKO_Trikot_Glory_kurzarm_back.jpg",
      description:
        "Klarer Look mit Vereinswappen. Die Glory-Trikotvorschau in Weiß mit schwarzen Details.",
    },
    {
      id: "vintage",
      name: "Trikot Vintage",
      type: "Kurzarm",
      color: "Grün / Weiß",
      front: "assets/JAKO_Trikot_Vintage_kurzarm_front.jpg",
      back: "assets/JAKO_Trikot_Vintage_kurzarm_back.jpg",
      description:
        "Fußball-Look mit Retro-Charakter. Die Vintage-Trikotvorschau in Grün und Weiß.",
    },
    {
      id: "iconic",
      name: "Kapuzenjacke Iconic",
      type: "Teamwear",
      color: "Grün / Grau",
      front: "assets/JAKO_Kapuzenjacke_Iconic.jpg",
      back: "assets/JAKO_Kapuzenjacke_Iconic_back.jpg",
      description:
        "Für den Weg zum Platz und die Zeit danach. Die Iconic-Kapuzenjacke in Grün und Grau.",
    },
  ],
  squadArchive: [
    { name: "Fabian Matschnigg", position: "Torwart" },
    { name: "Dominik Bicker", position: "Torwart" },
    { name: "Yasin Muslubas", position: "Torwart" },
    { name: "Dario Schierenberg", position: "Torwart" },
    { name: "David Kulina", position: "Torwart" },
    { name: "Marvin Schulz", position: "Abwehr" },
    { name: "Okan Isleyen", position: "Abwehr" },
    { name: "Patrick Herkt", position: "Abwehr" },
    { name: "Joshua Denk", position: "Abwehr" },
    { name: "Muhamed Demir", position: "Innenverteidiger" },
    { name: "Dincer Kahraman", position: "Mittelfeld" },
    { name: "Bassam Uygur", position: "Mittelfeld" },
    { name: "Mohammad Milad Sahebzada", position: "Mittelfeld" },
    { name: "Saher Ayhan", position: "Sturm" },
    { name: "Ahmet Cicek", position: "Sturm" },
  ],
};
